# 메트릭 서버 설치(delete 후 재설치 )
# kubectl delete -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fojf-ordersystem-deployment-hpa
  namespace: fojf-namespace
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fojf-ordersystem-deployment
  minReplicas: 1
  maxReplicas: 3
  # CPU 사용률이 30%를 넘으면 자동으로 스케일 아웃(테스트 목적이라 부하를 많이 주기 힘들어서 30으로 설정한 것, 실제 서비스에서는 70~80%로 설정)
  targetCPUUtilizationPercentage: 30

# 메트릭 서버와 HPA를 통한 pod 현황 조회
# kubectl get hpa fojf-ordersystem-deployment-hpa -n fojf-namespace -w

# 부하 간단 테스트
# 특정 pod에 접속
# while true; do curl -s http://fojf-ordersystem-service/product/list; done
