
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/ordermsa
    username: admin
    password: ${DB_PW}
    hikari: 
      maximum-pool-size: 1
  config:
    activate:
      on-profile: prod
    
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show_sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: fojf-redis-service
      port: 6379

  application:
    name: product-service

  kafka:
    kafka-server: kafka-service:9092
    consumer:
      #      group-id는 컨슈머 그룹을 식별하는 ID로서, 동일한 그룹 ID를 가진 컨슈머들은 메세지를 분담해서 consume
      #      그런데, 만약 컨슈머가 서로 다른 group-id를 가지고 한 topic을 consume하면 메세지를 각기 수신하는 pub/sub효과 발생
      group-id: product-group
      #      가장 처음 들어온 메세지 부터 읽기 시작(latest: 현시점 이후로 들어오는 메세지만 읽음)
      auto-offset-reset: earliest

cloud:
  aws:
    credentials:
      access-key: xx
      secret-key: yy
    region:
      static: ap-northeast-2
    s3:
      bucket: xx


server:
  port: 8080
# 0으로 설정시  0~65535 중 중복되지않는 port 임의로 설정

eureka:
  client:
    enabled: false
