apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fojf-apigateway-issuer
  namespace: fojf-namespace
spec:
  acme:
  # ca 서버 주소. 해당 서버를 통해 인증서 발행
    server: https://acme-v02.api.letsencrypt.org/directory
  # 인증서 만료 또는 갱신 필요시 알람 email
    email: john9823@naver.com
    privateKeySecretRef:
    # 인증서를 발급받기 위해 ca와 통신시에 사용되는 Secret 이름(중요X)
      name: fojf-apigateway-issuer-account-key
    solvers:
    - http01:
        ingress:
        # 도메인의 소유권을 확인하기 위해 cert-manager는 nginx기반의 ingress controller를 활용해 검증한다는 의미
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-fojf-shop-tls
  namespace: fojf-namespace
spec:
# cert-manager가 아래 secretName에서 지정한 이름으로 Secret을 생성
  secretName: server-fojf-shop-tls
  duration: 2160h #90day
  renewBefore: 720h #before 30day
  issuerRef:
  # ClusterIssuer의 이름을 참조
    name: fojf-apigateway-issuer
    kind: ClusterIssuer
  commonName: server.fojf.shop
  dnsNames:
  # 추가적인 서브도메인을 추가하고 싶은경우에 여기에 나열
  - server.fojf.shop
